### ISSUE TITLE
Snapchat crashes when zData activated

### ISSUE THREAD

**Issue by Philip6294** [kirbyfan64/zdata#1]
When you try to use the map it crashes sooner or later.
[logcat.txt](https://github.com/kirbyfan64/zdata/files/1223004/logcat.txt)

**Comment by refi64** [comment]
Hmm...I have a hunch of what causes this, but it'll take a bit to get around to checking myself (wisdom tooth extraction tomorrow...).

**Comment by refi64** [comment]
FWIW how did you log in to Snapchat? I'm trying to now, but it apparently doesn't work on rooted devices...

**Comment by Philip6294** [comment]
Snapchat checks SafetyNet on login, if your device doesn't pass it won't let you login. So you have to use something like Magisk(https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445)  to use snapchat and have Root Acces

**Comment by Philip6294** [comment]
Just Updated to the Latest Version and checked it again, it's now working.
