### ISSUE TITLE
App crashes after granting root access

### ISSUE THREAD

**Issue by RandomTypek** [kirbyfan64/zdata#2]
After opening the app and granting root access, it immediately closes. Tested on a Xiaomi Mi4 running xiaomi.eu MIUI 7.6.14 based on Android 6.0.1.
[alogcat.2017-08-15-12-22-55+0200.txt](https://github.com/kirbyfan64/zdata/files/1224858/alogcat.2017-08-15-12-22-55.0200.txt)

**Comment by zputnyq** [comment]
It's my 1st time on github & taking a logcat, sorry if there is a mistake.

Currently I experience crash/force close but succeed in granting root.
The crash happens on "loading tools" proccess, when the app entering "loading tools" it suddenly closed without notification.
My device is acer Z205
Mtk6572
Kitkat 4.4.2 (stock).

Here's the logcat
[2017-08-15-20-58-11.txt](https://github.com/kirbyfan64/zdata/files/1225306/2017-08-15-20-58-11.txt)

I really appreciate this app

Regards

**Comment by refi64** [comment]
@RandomTypek @zputnyq Can you try zdata v0.1.2 and post a new logcat? I changed some logging related stuff, so now it should give a more descriptive log that I can use.

**Comment by zputnyq** [comment]
@kirbyfan64
Tried v0.1.2, no crash/fc but loading application list seems unable to finish.
my apology, I forgot to add some infos
I am using xposed 2.6.1 by solarwarez and SuperrSU 2.65 by chainfire.

Here is the newest logcat

[2017-08-17-14-04-19.txt](https://github.com/kirbyfan64/zdata/files/1230456/2017-08-17-14-04-19.txt)

Hope it could help

**Comment by RandomTypek** [comment]
@kirbyfan64 Thank you for your work, the app doesn't crash anymore but I'm facing the same issue as @zputnyq - the app gets stuck at the "loading application list" screen.
[alogcat.2017-08-17-12-03-38+0200.txt](https://github.com/kirbyfan64/zdata/files/1230993/alogcat.2017-08-17-12-03-38.0200.txt)

**Comment by refi64** [comment]
@RandomTypek @zputnyq Try this APK: http://ge.tt/7eIcbCm2

**Comment by zputnyq** [comment]
V0.1.3 could load app list but it fails on compressing app's data.
Here's I include logcat, screenshot of supersu's log & screenshot on compressing failure
[2017-08-18-01-51-03.txt](https://github.com/kirbyfan64/zdata/files/1232302/2017-08-18-01-51-03.txt)
![screenshot_2017-08-18-01-46-03](https://user-images.githubusercontent.com/31039796/29428815-c10adc28-83b8-11e7-9e06-545db8796f47.png)
![screenshot_2017-08-18-01-52-24](https://user-images.githubusercontent.com/31039796/29428832-d0f5da16-83b8-11e7-8d70-a1e8fa14ce84.png)

Hope it could help
I really appreciate it

**Comment by refi64** [comment]
@zputnyq Almost there! One last thing to check: what do you get if you run these two commands from a root-enabled shell:

```
stat -c %U /data/data/com.facebook.katana
ls -ld /data/data/com.facebook.katana
```

**Comment by zputnyq** [comment]
@kirbyfan64
I used terminal, grant supersu & type the commands u privided,
then I got this

![screenshot_2017-08-18-02-56-18](https://user-images.githubusercontent.com/31039796/29431415-0d997af0-83c2-11e7-9890-896af0e04a08.png)

**Comment by refi64** [comment]
@zputnyq Try this instead:

```
ls -l /data/data
```

and note that the `-l` is a lowercase L, *not* a number 1.

**Comment by zputnyq** [comment]
I got this
![screenshot_2017-08-18-11-04-50](https://user-images.githubusercontent.com/31039796/29443860-29c6fb9c-8405-11e7-9b99-60da1a464fca.png)

**Comment by RandomTypek** [comment]
@kirbyfan64 Same issue as @zputnyq , I'm attaching a logcat + outputs of the three commands you mentioned (I changed com.facebook.katana to the name of the app I tried to compress, Google Street View in my case)
[alogcat.2017-08-18-11-42-39+0200.txt](https://github.com/kirbyfan64/zdata/files/1234069/alogcat.2017-08-18-11-42-39.0200.txt)
![screenshot_2017-08-18-12-05-04-581_jackpal androidterm](https://user-images.githubusercontent.com/31035586/29454871-1f7838c2-840f-11e7-8423-a214a1c0bc58.png)
[terminal.txt](https://github.com/kirbyfan64/zdata/files/1234073/terminal.txt)

**Comment by refi64** [comment]
Aaaaaaaah @RandomTypek @zputnyq ...you're both using Android Marshmallow, aren't you? zdata requires some stuff that isn't easily available for Marshmallow. I can try making all that stuff work, but it's going to take a bit longer than I was hoping...

That being said, you actually stumbled across two slightly different issues. It wasn't working for @zputnyq because I was accidentally assuming that Busybox was installed, even though it sometimes isn't. I *have* been able to fix that, at least.

**Comment by RandomTypek** [comment]
@kirbyfan64 Well that's not good to hear.. Yes, I am indeed using Marshmallow. It would be great if you managed to make it work, but you don't have to waste your time with it if it's too hard or something. I'm glad to hear that you've been able to fix @zputnyq 's issue.

**Comment by refi64** [comment]
@RandomTypek Two months later...and I believe I have a Marshmallow-compatible version of zdata! Here's a link: https://nofile.io/f/DaOZnVQukxo/app-release.apk

This is very much alpha-quality stuff, but I wanted to see if you could try it out!

**Comment by RandomTypek** [comment]
@kirbyfan64 Oh, nice, great work! I, unfortunately, can't test it though, I have recently installed an Oreo custom ROM on my phone, and even the older version of the app works on that, so yeah. I could try it using Android 5 (my tablet is running that), or with Android x86 on my PC, but I'm not sure if that would work.

**Comment by refi64** [comment]
@RandomTypek Well, I randomly tried a build with Android 5, and it appears to actually have worked: https://file.io/013eA7

A lot of the previous things holding back older Android release support were NDK bugs that have since been fixed in the betas.

**Comment by RandomTypek** [comment]
@kirbyfan64 Link doesn't work, Error 404

**Comment by refi64** [comment]
@RandomTypek Crap...try [this one](https://file.io/b2DOen) instead.

**Comment by RandomTypek** [comment]
@kirbyfan64 Weird, the link worked this time, but I can't even install the apk, it just shows the package parse error. The weird thing is that the Marshmallow version did install but didn't work. It doesn't appear to be corrupted, as the installer opens fine on Oreo. Also, I should probably mention that my tablet is on x86_64 architecture if that makes any difference.

**Comment by refi64** [comment]
@RandomTypek *I swear this is the last time I use random file hosting sites...* Here's another one: https://drive.google.com/open?id=0B3RBF3Zy7CAXUk5OYkwycU5KRjg

This is Google Drive. It better freaking work...

**Comment by RandomTypek** [comment]
@kirbyfan64 App got installed fine but didn't work, here is a logcat and the SuperSU log (sorry for the delay, I was very busy during the week and didn't have time to test)
[alogcat.2017-10-21-14-52-07+0200.txt](https://github.com/kirbyfan64/zdata/files/1404105/alogcat.2017-10-21-14-52-07.0200.txt)
![screenshot_2017-10-21-14-54-13](https://user-images.githubusercontent.com/31035586/31851956-77846c46-b670-11e7-8e5f-8df7b11d65e4.jpg)

**Comment by refi64** [comment]
@RandomTypek Hmm...[try using this one now](https://drive.google.com/open?id=0B3RBF3Zy7CAXUk5OYkwycU5KRjg).

**Comment by RandomTypek** [comment]
@kirbyfan64 I got this now:
![screenshot_2017-10-26-19-49-20](https://user-images.githubusercontent.com/31035586/32068709-3e32c634-ba87-11e7-8e9a-d4b1c5c67587.jpg)
[alogcat.2017-10-26-19-48-08+0200.txt](https://github.com/kirbyfan64/zdata/files/1419487/alogcat.2017-10-26-19-48-08.0200.txt)

**Comment by refi64** [comment]
*Wow I'm an idiot*...I was sending you ARM binaries for your X86 tablet. *facepalm*

So now, *here* should be one that works: https://drive.google.com/open?id=0B3RBF3Zy7CAXUk5OYkwycU5KRjg

**Comment by RandomTypek** [comment]
@kirbyfan64 I'm sorry for the frustration, but no, it still doesn't work. Now it doesn't even load the GUI, just a black screen. I can only attach a logcat now as it didn't even ask for root permissions, hopefully, that'll be enough.
[alogcat.2017-10-29-21-45-22+0100.txt](https://github.com/kirbyfan64/zdata/files/1425493/alogcat.2017-10-29-21-45-22.0100.txt)

**Comment by refi64** [comment]
@RandomTypek I should be apologizing to you, since I'm making you try all these binaries that aren't working yet. ;)

I had been trying to see if I could add proper X86 support to the app without relying on debug binaries...but it looks like that won't be the case. Here's a debug binary, and *this* one should work (how about I shut up before I jinx it): https://drive.google.com/open?id=1lZGdky6C196tAtiqkLPw7ZW9kBIunpUL

**Comment by RandomTypek** [comment]
@kirbyfan64 Well, the app loaded now, but I seem to be getting the same error as before:
![screenshot_2017-11-10-19-47-16](https://user-images.githubusercontent.com/31035586/32673898-24f182ac-c651-11e7-8125-23921b526290.jpg)
[alogcat.2017-11-10-19-45-12+0100.txt](https://github.com/kirbyfan64/zdata/files/1462409/alogcat.2017-11-10-19-45-12.0100.txt)

**Comment by refi64** [comment]
@RandomTypek Just fixed that; turns out, zdata was accidentally picking ARM binaries on X64 platforms. This one should have fixed that: https://upspin.refi64.com/rymg19@gmail.com/pub/zdata/testing/zdata-11-17-17-debug.apk

**Comment by RandomTypek** [comment]
@kirbyfan64 Okay, it appears like it almost worked this time, didn't get the usual internal script error or whatever, the app closed and then immediately opened itself back up. However, I noticed that it still said "Disabled" next to the app I tried to compress (Google Street View) and the size of the app didn't change much (I'm not sure whether it changed at all, I forgot to check the original size before trying to compress). 
Here are the logs:
![screenshot_2017-11-17-17-17-30](https://user-images.githubusercontent.com/31035586/32957798-fb742896-cbbc-11e7-89e6-06d87b0f12bc.jpg)
![screenshot_2017-11-17-17-17-43](https://user-images.githubusercontent.com/31035586/32957811-0115c584-cbbd-11e7-93cf-2d311c717bfa.jpg)
![screenshot_2017-11-17-17-17-57](https://user-images.githubusercontent.com/31035586/32957825-04dfd196-cbbd-11e7-9416-c2400124b57a.jpg)
[alogcat.2017-11-17-17-15-01+0100.txt](https://github.com/kirbyfan64/zdata/files/1483020/alogcat.2017-11-17-17-15-01.0100.txt)

**Comment by refi64** [comment]
> the app closed and then immediately opened itself back up

Yeah that's (unfortunately) an intentional thing that should be fixed next release.

Now, what happens if you run `ls -1 /data/data/com.refi64.zdata.app/app_flutter/storage` from a root shell? zdata checks the existence of the app data storage directory to determine if it's enabled for that app. I'm guessing somehow the command I'm using for that isn't returning correctly...

**Comment by RandomTypek** [comment]
@kirbyfan64 I just found out that both Maps and Street View were actually system apps on the tablet, I got confused because, on my phone, I had to install them manually from Google Play. I thought that might be the problem, so I decided to try it on Doodle Jump instead. The app's size decreased by about 2 MB, not sure if it actually compressed it or if that's just because zdata cleared its data. Here is what I got after running the command, also I got a bit different log this time, the log after that is the same as before though. It says "Disabled" next to Doodle Jump as well, by the way.
![screenshot_2017-11-17-18-19-04](https://user-images.githubusercontent.com/31035586/32960584-b9e628c6-cbc5-11e7-9f52-39b1c261f540.jpg)
![screenshot_2017-11-17-18-20-22](https://user-images.githubusercontent.com/31035586/32960587-be3ed62a-cbc5-11e7-9d81-a401fd48b046.jpg)

**Comment by refi64** [comment]
@RandomTypek In the `ls -1`, that's the number 1, not the lowercase letter L...

**Comment by RandomTypek** [comment]
@kirbyfan64 I just get "ls: Unknown option '-1'. Aborting." when I run that

**Comment by refi64** [comment]
Ah, there's the problem: your Android phone's `ls` doesn't support the `-1` option (I'm guessing that was added in a later release), so zdata never gets any enabled items.

Try this one: https://upspin.refi64.com/rymg19@gmail.com/pub/zdata/testing/zdata-11-17-17-debug.2.apk

**Comment by RandomTypek** [comment]
@kirbyfan64 Yep, it's working perfectly fine now, it now says "Enabled" next to the app and even disabling zdata seems to work, the device reboots and after that, it says "Disabled" again. Great job!

**Comment by RandomTypek** [comment]
@kirbyfan64 Also, here are some logs with errors in them, not sure if these are important but I'm sending them just in case.
![screenshot_2017-11-17-20-28-45](https://user-images.githubusercontent.com/31035586/32965317-6999b7c8-cbd6-11e7-8f6a-4ea3fc4bf482.jpg)
![screenshot_2017-11-17-20-29-07](https://user-images.githubusercontent.com/31035586/32965333-7340cbf4-cbd6-11e7-9e10-c29d2437d94f.jpg)

**Comment by refi64** [comment]
@RandomTypek The `mountall.sh` failure is actually really bad, because then zdata will say it's enabled, but it will never have activated on that boot. Thanks for the log!

The `fusermount` failure happens a lot, which is why disabling app reboots the device anyway. I removed the command that caused the *Failed* message because it was pretty pointless anyway.

Here's the result: https://upspin.refi64.com/rymg19@gmail.com/pub/zdata/testing/zdata-11-17-17-debug.3.apk

*Now* this one should work perfectly!

**Comment by RandomTypek** [comment]
@kirbyfan64 The mountall log still looks a bit suspicious, so here it is.

Also, is there any way to check if the compression is actually working?
![screenshot_2017-11-18-12-01-07](https://user-images.githubusercontent.com/31035586/32979681-6d865fd8-cc5a-11e7-9235-7da000a1971b.jpg)

**Comment by refi64** [comment]
@RandomTypek Whoops, that was my bad...

*This* version should definitely work: https://upspin.refi64.com/rymg19@gmail.com/pub/zdata/testing/zdata-11-20-17-debug.apk

Also, to tell if it's working, try running `mount | grep com.my.app.name` and check if you see a row mentioning *fusecompress*.

**Comment by RandomTypek** [comment]
@kirbyfan64 Mountall log still looks like this:
![screenshot_2017-11-22-15-40-49](https://user-images.githubusercontent.com/31035586/33133803-3866375a-cf9e-11e7-9a21-35638cd5b35b.jpg)

Running "mount | grep" didn't seem to do anything, so I tried running just "mount" and I did see my app on the list with "fusecompress" next to it, after restarting it was not there anymore (I suppose that's because of the mountall failure)

**Comment by refi64** [comment]
@RandomTypek WTH, I fixed that already...

I'm guessing Flutter didn't built it correctly. I did a clean build, at *this* one should work: https://upspin.refi64.com/rymg19@gmail.com/pub/zdata/testing/zdata-11-22-17-debug.apk

**Comment by RandomTypek** [comment]
@kirbyfan64 Awesome, everything seems to be working now! Here are all the logs:
![screenshot_2017-11-22-18-47-51](https://user-images.githubusercontent.com/31035586/33142704-a4146d82-cfb7-11e7-8605-e8a91e8fe911.jpg)
![screenshot_2017-11-22-18-48-08](https://user-images.githubusercontent.com/31035586/33142711-acd5876c-cfb7-11e7-97bd-08c97161db24.jpg)
![screenshot_2017-11-22-18-54-40](https://user-images.githubusercontent.com/31035586/33142721-b61711d8-cfb7-11e7-992f-71e5470975cd.jpg)
![screenshot_2017-11-22-18-55-11](https://user-images.githubusercontent.com/31035586/33142729-bc6c140c-cfb7-11e7-9e27-d24cb829e6ec.jpg)

This is what happens after reboot when zdata is completely disabled (not enabled on any app):
![screenshot_2017-11-22-18-54-57](https://user-images.githubusercontent.com/31035586/33142812-fef9db92-cfb7-11e7-8905-c4645f99dd22.jpg)

One more thing I noticed: When I enable or disable zdata, the scripts get run multiple times, usually like 3 times, not sure if that's intended. The mountall script only seems to run once though.

**Comment by refi64** [comment]
@RandomTypek SWEET!

> When I enable or disable zdata, the scripts get run multiple times, usually like 3 times, not sure if that's intended.

Actually, no...looks like that's been a bug for ages, but it actually caused trouble until I upgraded Flutter...

Anyhow, here's a version that should fix the multiple-running thing, as well as the error that occurred when you disabled zdata altogether (though it shouldn't have been causing any trouble to begin with): https://upspin.refi64.com/rymg19@gmail.com/pub/zdata/testing/zdata-11-22-17-debug.2.apk

**Comment by RandomTypek** [comment]
@kirbyfan64 Can confirm, these bugs are fixed, however, I just noticed that the space savings thing seems a bit off lol
![screenshot_2017-11-23-15-19-57](https://user-images.githubusercontent.com/31035586/33177832-4e8ed8ae-d064-11e7-885a-2a55954cabb4.jpg)
![screenshot_2017-11-23-15-24-33](https://user-images.githubusercontent.com/31035586/33177845-557416de-d064-11e7-86b6-a0e2b7c0ec4d.jpg)

Also, I downloaded that game just to check the compression: 
 - Without compression and after downloading all data - 789 MB
 - Immediately after compression - 128 MB (it deleted the data)
 - With compression and data - 789 MB (it didn't change at all)

So, I'm really not sure at this point if the compression is working. Do you possibly know any apps confirmed to be compressible by zdata, so I can test?

**Comment by refi64** [comment]
Hmm...this can either be:

- Your phone is calculating the size in a certain way that's ignoring zdata's compression, and the compression isn't being calculated correctly on your device.
- The app is storing its data in a different location.
- The app may have already tried compressing its data, which would mean zdata doesn't have much to do.

I know that zdata for sure works on Sword Art Online: Memory Defrag. This is how the statistics look after signing up for the game and playing for a bit:

![](https://i.imgur.com/d7ykAyo.png)

**Comment by RandomTypek** [comment]
@kirbyfan64 Okay, it is working for sure! I guess most of the apps I use can't be compressed then, oh well
![screenshot_2017-11-24-16-16-18](https://user-images.githubusercontent.com/31035586/33216666-18531b0c-d135-11e7-8c7f-7ad7f223fb52.jpg)

**Comment by refi64** [comment]
@RandomTypek Ah, rip. Looks like something else to add to the feature list!! (At this point I'm pretty sure that game actually saves its data to the SD card, which is why it doesn't show zdata working.)
